INSERT INTO tb_regime(short_name, description) VALUES ('CLT', 'Consolidação das Leis do Trabalho')
INSERT INTO tb_regime(short_name, description) VALUES ('EREC', 'Encargos sob a Responsabilidade da Empresa Contratada')
INSERT INTO tb_regime(short_name, description) VALUES ('ETR', 'Estatuto do Trabalhador Rural')
INSERT INTO tb_regime(short_name, description) VALUES ('REA', 'Regime Especial para Aprendizagem')
INSERT INTO tb_regime(short_name, description) VALUES ('RTT', 'Regime de Trabalho Temporário')
INSERT INTO tb_regime(short_name, description) VALUES ('TST', 'Trabalhadores em Serviços Terceirizados')

INSERT INTO tb_cluster(nickname, description) VALUES ('A&C', 'Setores Adiministrativos e Comerciais')
INSERT INTO tb_cluster(nickname, description) VALUES ('SGA', 'Setores Gerais e Auxiliares')
INSERT INTO tb_cluster(nickname, description) VALUES ('SPR', 'Setores Produtivos')

INSERT INTO tb_map_edition(edition_number, production_shift, moment, description) VALUES ('Edição 1', 'Turno 1', '2023-01-15', 'Edição inicial conforme definição da diretoria')
INSERT INTO tb_map_edition(edition_number, production_shift, moment, description) VALUES ('Edição 2', 'Turno 1', '2023-03-01', 'Impacto do dissídio coletivo 2023')
INSERT INTO tb_map_edition(edition_number, production_shift, moment, description) VALUES ('Edição 3', 'Turno 1', '2023-07-24', 'Ajustes sobre o DGF')
INSERT INTO tb_map_edition(edition_number, production_shift, moment, description) VALUES ('Edição 4', 'Turno 2', '2023-07-31', 'Inclusão do segundo turno')
INSERT INTO tb_map_edition(edition_number, production_shift, moment, description) VALUES ('Edição 5', 'Turno 3', '2023-08-05', 'Inclusão do terceiro turno')

INSERT INTO tb_depreciation_period(asset_type, timeframe_month) VALUES ('Construção civil', 240)
INSERT INTO tb_depreciation_period(asset_type, timeframe_month) VALUES ('Máquinas e Equipamentos', 120)
INSERT INTO tb_depreciation_period(asset_type, timeframe_month) VALUES ('Veículos', 60)
INSERT INTO tb_depreciation_period(asset_type, timeframe_month) VALUES ('Equipamentos eletrônicos', 36)

INSERT INTO tb_category(name) VALUES ('REMUNERAÇÕES');
INSERT INTO tb_category(name) VALUES ('DEPRECIAÇÕES');
INSERT INTO tb_category(name) VALUES ('FORÇA MOTRIZ');
INSERT INTO tb_category(name) VALUES ('DGF');

INSERT INTO tb_category(name, category_id) VALUES ('SALÁRIOS', 1);
INSERT INTO tb_category(name, category_id) VALUES ('ENCARGOS', 1);
INSERT INTO tb_category(name, category_id) VALUES ('MATERIAIS DE OPERAÇÃO', 4);
INSERT INTO tb_category(name, category_id) VALUES ('COMBUSTÍVEIS PARA PROCESSO', 4);
INSERT INTO tb_category(name, category_id) VALUES ('FERRAMENTAS PERECÍVEIS', 4);
INSERT INTO tb_category(name, category_id) VALUES ('UTILIDADES (LUZ/TELEFONE/ÁGUA)', 4);
INSERT INTO tb_category(name, category_id) VALUES ('MANUTENÇÃO', 4);
INSERT INTO tb_category(name, category_id) VALUES ('ALUGUÉIS, SEGUROS E TAXAS', 4);
INSERT INTO tb_category(name, category_id) VALUES ('DESPESAS DIVERSAS', 4);

INSERT INTO tb_trigger(trigger_date, ec_level_type, map_edition_id) VALUES ('2022-11-15', null, 1)
INSERT INTO tb_trigger(trigger_date, ec_level_type, map_edition_id) VALUES ('2022-08-01', 0, 2)
INSERT INTO tb_trigger(trigger_date, ec_level_type, map_edition_id) VALUES ('2023-07-01', 1, 3)
INSERT INTO tb_trigger(trigger_date, ec_level_type, map_edition_id) VALUES ('2023-07-01', 3, 3)
INSERT INTO tb_trigger(trigger_date, ec_level_type, map_edition_id) VALUES ('2023-07-01', 4, 3)
INSERT INTO tb_trigger(trigger_date, ec_level_type, map_edition_id) VALUES ('2023-08-01', 4, 4)
INSERT INTO tb_trigger(trigger_date, ec_level_type, map_edition_id) VALUES ('2023-08-05', 4, 5)

INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('SALARIOS E ORDENADOS MOD/MOI TURNO PRINCIPAL', 906815.72, null, null, '2022-11-15', 'Balanço', 5, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('ENCARGOS ESPECÍFICOS PARA O ESTADO', 672585.21, null, null, '2022-11-15', 'Balanço', 6, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('BENEFÍCIOS ADICIONAIS POR OPÇÃO DA EMPRESA', 0.0, '4.1.02.02.03.11', 1823, '2022-11-15', 'Balanço', 6, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MATERIAL DE CONSUMO PRODUÇÃO', 48068.90, '4.1.02.02.06.17', 1830, '2022-11-15', 'Balanço', 7, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MATERIAL DE EXPEDIENTE P/ PRODUÇÃO', 2173.77, '4.1.02.02.06.19', 1892, '2022-11-15', 'Balanço', 7, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('COMBUSTIVEIS E LUBRIFICANTES PARA PRODUÇÃO', 15855.7, '4.1.02.02.06.20', 44035, '2022-11-15', 'Balanço', 8, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('ENERGIA ELETRICA', 92034.69, '4.1.02.02.05.02', 1700, '2022-11-15', 'Balanço', 10, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('AGUA / PRODUÇÃO', 5419.83, '4.1.02.02.06.10', 1694, '2022-11-15', 'Balanço', 10, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUT DE PREDIOS INSTAL. PROD', 29402.38, '4.1.02.02.06.01', 1731, '2022-11-15', 'Balanço', 11, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUTENÇÃO C/FERRAMENTAL / PROD', 82386.35, '4.1.02.02.06.03', 1897, '2022-11-15', 'Balanço', 11, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUT DE VEICULOS/ PROD', 3219.33, '4.1.02.02.06.21', 1878, '2022-11-15', 'Balanço', 11, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUT DE MAQ E EQUIPAMENTOS/PROD', 72560.16, '4.1.02.02.06.25', 1724, '2022-11-15', 'Balanço', 11, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUTENÇÃO MOVEIS E UTENS - PROD', 167.33, '4.1.02.02.06.46', 4920, '2022-11-15', 'Balanço', 11, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('ALUGUEL PREDIAL', 183279.67, '4.1.02.02.05.08', 1687, '2022-11-15', 'Balanço', 12, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('SEGUROS BENS DE PRODUÇÃO', 379.4, '4.1.02.02.05.21', 4035, '2022-11-15', 'Balanço', 12, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MAT DE SEGUR. NO TRABALHO PROD (EPI)', 533.47, '4.1.02.02.06.02', 1816, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('PEDAGIO E ESTACIONAMENTO - PROD', 0.0, '4.1.02.02.05.11', 45834, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MATERIAL  LIMPEZA PROD', 2364.8, '4.1.02.02.06.32', 45919, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('COMUNICAÇÃO E SISTEMAS PROD', 3047.61, '4.1.02.02.06.42', 4588, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('UNIFORMES E EQUIP. PROTEÇÃO - PROD.', 71494.16, '4.1.02.02.03.06', 4802, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS COM VIAGEM - PROD', 7262.19, '4.1.02.02.03.07', 45827, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('CONSUMO INTERNO/PROD', 330990.13, '4.1.02.02.06.05', 46664, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('HORA EXTRA - ADM', 7437.51, '4.2.01.02.01.11', 4155, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('SEGUROS VIDA E PREVIDENCIA ADM', 2850.0, '4.2.01.02.03.08', 45513, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('REFEIÇÕES E LANCHES ADM', 4.99, '4.2.01.02.03.10', 4169, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS BANCARIAS', 2869.95, '4.2.01.02.05.90', 2486, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('BRINDES ADM', 6190.77, '4.2.01.02.05.70', 4200, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('COMBUST E LUBRIFICANTES/ADM', 1842.24, '4.2.01.02.04.09', 2394, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS DE INTERNET', 2374.52, '4.2.01.02.05.37', 461634, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('LOCACAO DE BENS MOVEIS/VEICULO ADM', 9253.62, '4.2.01.02.05.52', 461566, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS MARKETING ADM - PRODUTOS LOGOMARCA', 739.6, '4.2.01.02.05.56', 4269, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('IMPOSTOS E TAXAS', 3036.77, '4.2.01.02.05.29', 45989, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUT DE PREDIOS E INSTAL./ADM', 131.66, '4.2.01.02.04.02', 2165, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUTENÇÃO MOVEIS E UTENS - ADM', 22.66, '4.2.01.02.04.12', 4921, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MANUTENCAO E CONSERV. INFORMATICA', 0.0, '4.1.02.02.06.12', 462136, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MATERIAL  E LIMPEZA ADM', 1032.86, '4.2.01.02.05.26', 45926, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('SERVIÇOS TERCEIROS - ADM - TERCEIRIZADOS', 8995.78, '4.2.01.02.01.12', 5193, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('ASSESSORIA  CONTAB/ CONSU./ADM', 3277.41, '4.2.01.02.05.01', 2110, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('PRESTACAO SERVICOS TERCEIROS ADM - RPA', 4000.0, '4.2.01.02.05.22', 462518, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('PRESTACAO SERVICOS TERCEIROS ADM', 69074.71, '4.2.01.02.05.23', 45674, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('INDENIZACOES PROCESSOS TRABALHISTAS', 0.0, '4.2.01.02.05.67', 47470, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('FRETES, CARRETOS E MALOTES', 37.27, '4.2.01.02.05.41', 461580, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS POSTAIS/ADM', 108.53, '4.2.01.02.05.04', 2189, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('PROCESSOS TRABALHISTAS ', 6480.19, '4.2.01.02.05.05', 462044, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS DE VIAGENS/ADM', 13847.42, '4.2.01.02.05.08', 2264, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MATERIAL DE EXPEDIENTE/ADM', 6186.13, '4.2.01.02.05.09', 2271, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('MATERIAL DE CONSUMO ADM', 10832.39, '4.2.01.02.05.13', 2370, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS CARTORIAIS', 7.61, '4.2.01.02.05.20', 45520, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS INDEDUTIVEIS', 375.0, '4.2.01.02.05.28', 46, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS LEGAIS E JUDICIAIS', 1500.0, '4.2.01.02.05.33', 461498, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('UNIFORMES E EQUIP. PROTEÇÃO - ADM', 799.82, '4.2.01.02.03.04', 4161, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('DESPESAS C/TELEFONE / ADM', 2596.64, '4.2.01.02.04.04', 2196, '2022-11-15', 'Balanço', 13, 1)
INSERT INTO tb_expense(description, month_amount, accounting_code, short_code, released_date, origen_costs, category_id, trigger_id) VALUES ('COMUNICACOES E SISTEMAS ADM', 13580.26, '4.2.01.02.05.54', 461627, '2022-11-15', 'Balanço', 13, 1)

INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Gestão Corporativa', 208.74, 3.3, null, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Diretoria ', 27.72, 0, 1, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Comercial (Vendas/Marketing/Finanças/Custos/Fiscal) ', 40.9, 1.4, 1, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Compras Sala da Aline e do Makson', 7.85, 0.4, 1, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('RH Relações Humanas e Industriais ', 51.29, 1.2, 1, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Sistema (COORD SOLDA)', 24.85, 0.1, 1, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Data Center', 53.06, 0.1, 1, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Portaria', 3.07, 0.1, 1, 1)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Administração Industrial', 722.03, 5.8, null, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Planejamento e Controle da Produção (PCP) ', 51.76, 1.4, 9, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('PCP (apenas a parte do Paulo, Ketlin e demais)', 26.55, 0.1, 9, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Logística Administrativo ', 55.88, 2, 9, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Logística Estoque ', 417.26, 1, 9, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Logística Carregamento ', 56.99, 0.1, 9, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Manutenção de Máquinas e Ferramental ', 66.65, 1, 9, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Administração Predial Manutenção de Edificio ', 46.94, 0.2, 9, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Qualidade/Inspeção', 240.12, 1.9, null, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Laboratorio ', 46.02, 0.8, 17, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Quality gate (componentes)', 18.04, 0.1, 17, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Quality gate (solda)', 16.92, 0.1, 17, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Quality gate (pintura)', 25.2, 0.1, 17, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Qualidade Assegurada (Tridimensional/Metrologia) ', 42.68, 0.8, 17, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Recebimento de Componentes', 91.26, 0, 17, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Engenharia', 193.2, 7.6, null, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('ENGENHARIA', 42.82, 1.6, 24, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('ENGENHARIA ', 103.33, 4, 24, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Engenharia Protótipo', 47.05, 2, 24, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES (' Outros Custos Gerais e Auxiliares', 1906.72, 1.6, null, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Vestiário feminino ', 70.39, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Vestiário masculino ', 71.7, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Banheiro masculino 1 ', 15.31, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Banheiro masculino 2', 15.21, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Banheiro feminino ', 15.21, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Almoxarifado Estoque ', 580.81, 0.6, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Recebimento de tubos ', 472.443, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Estoque interno', 628.28, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Sala Joel', 13.09, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Wilson', 7.5, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Hirlando', 16.78, 0.1, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Computadores da produção', 0, 0, 28, 2)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Componentes', 709.094882, 321.4, null, 3)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Solda (manual, robô e muffler)', 443.577641, 532.8, null, 3)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Encapsulado', 21.474653, 26.1, null, 3)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Braços ', 200.7, 1, null, 3)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Pintura', 389.80282, 142.8, null, 3)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Tampografia', 32.28, 1.5, null, 3)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Expedição (área de embalagem)', 1053.86, 0.5, null, 3)
INSERT INTO tb_sector(name, dimension, energy_usage, sector_id, cluster_id) VALUES ('Expedição (área de expedir peça)', 884.71, 0.5, null, 3)

INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('185672', 'Adelyn', 'Hickman', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192792', 'Jayson', 'Lang', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192330', 'Alisson', 'Harmon', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('176682', 'Aldo', 'Reis', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('176729', 'Yandel', 'Lanças', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('154166', 'Micah', 'Fitzgerald', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('162703', 'Carlie', 'Bryan', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('140735', 'Lina', 'Zavala', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('127195', 'Haleigh', 'Inglês', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('150234', 'Louis', 'Perkins', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('155680', 'Madden', 'Burke', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('171996', 'Saniya', 'Taylor', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('198325', 'Paciência', 'Olson', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('174686', 'Malaki', 'Sábio', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('195422', 'Cailyn', 'Winters', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134455', 'Abigail', 'Smith', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134526', 'Diamante', 'Santiago', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('164660', 'Sara', 'Watkins', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('120326', 'Harmonia', 'Hardy', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('144215', 'Nylah', 'Graham', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('159146', 'Cristina', 'Rollins', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('132418', 'Tyshawn', 'Dyer', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('170164', 'Annika', 'Wiley', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('156875', 'Cassandra', 'McKinney', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('163769', 'Martin', 'Haley', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('116667', 'Clarissa', 'Greer', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('183868', 'Jakayla', 'Savage', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('172815', 'Ali', 'Semanas', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('132749', 'Amari', 'Levine', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169811', 'Zachary', 'Mills', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('167572', 'Kaleb', 'Arnold', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('191029', 'Jane', 'Colina', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('158819', 'Riley', 'Parrish', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('197273', 'Alan', 'Klein', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('112785', 'Yadiel', 'Mclaughlin', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('146686', 'Cole', 'Dennis', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('168743', 'Júlio', 'Valter', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('127396', 'Máximo', 'Moreno', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('165009', 'Valery', 'Miles', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('122646', 'Chave', 'Maxwell', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('119854', 'Princesa', 'Davies', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('197775', 'Beatriz', 'Conner', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('147424', 'Malia', 'Chang', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('187676', 'Payton', 'Bell', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('173920', 'Nancy', 'Maddox', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('112814', 'Marlee', 'Blackwell', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('139668', 'Lucy', 'Neil', 2, 3976.57, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('183156', 'Londres', 'Castañeda', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('135427', 'Déja', 'Patel', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('196137', 'Tori', 'Flores', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142602', 'Savanah', 'Mathis', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('180001', 'Marshall', 'Rogers', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('189490', 'Olivia', 'Durán', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('184411', 'Nikolas', 'Mcknight', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('196443', 'Tristan', 'Nielsen', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('185061', 'Hugh', 'Pennington', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('178289', 'Ismael', 'Rowe', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('147166', 'Sérgio', 'Shea', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('121281', 'Braden', 'Cameron', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('157144', 'Jonathan', 'Inglês', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('128770', 'Allisson', 'Bray', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('179509', 'Kaylah', 'Merritt', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134358', 'Monserrate', 'Mayer', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('129294', 'Emmett', 'Mosley', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192383', 'Dennis', 'King', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192355', 'Alisson', 'Cantrell', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134267', 'Coby', 'Bowman', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('109872', 'Pedro', 'Yates', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('186250', 'Juliana', 'Osborne', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('114576', 'Rhianna', 'Caim', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('145043', 'Atticus', 'Knapp', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('131635', 'Payten', 'Hurst', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('170852', 'Poderes', 'de', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192777', 'Glenn', 'McGuire', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('139731', 'Jack', 'Watkins', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('188686', 'Aisha', 'Mcmahon', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('110856', 'Delane', 'Thomas', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142951', 'Braedon', 'Gates', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('137833', 'Bentley', 'Márquez', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('111403', 'Keely', 'Pham', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('190694', 'Skylar', 'Walton', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('195575', 'Yadira', 'Huerta', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('166563', 'Curtis', 'Preto', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('141204', 'Jaiden', 'Atkinson', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('143186', 'Hugo', 'Pennington', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('145970', 'Ciara', 'Chang', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('119469', 'Nico', 'Rosário', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('113765', 'Raina', 'Gilberto', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('151469', 'Jordyn', 'Obrien', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('140683', 'Matheus', 'Dean', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('171084', 'Emerson', 'Galvan', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('115120', 'Pamela', 'Osborne', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('144654', 'Kiara', 'Cobb', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('195080', 'Christopher', 'Cunningham', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('181287', 'Travis', 'Rosário', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('149604', 'Keon', 'Kerr', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('118072', 'Bethany', 'Chase', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('179424', 'Reid', 'Caçador', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('195283', 'Zariah', 'Dillon', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('190371', 'Laci', 'Velez', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('164630', 'Savanah', 'Calhoun', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('122592', 'Diya', 'Delacruz', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('141464', 'Dakota', 'McIntyre', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('125420', 'Bola', 'de', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('118134', 'Ramiro', 'Nielsen', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('132015', 'Camren', 'Campos', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('141024', 'Liam', 'Carr', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('180584', 'Holden', 'Lewis', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('197034', 'Janelle', 'Galvan', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('126013', 'Afonso', 'Dickson', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('168337', 'Kristian', 'Hicks', 1, 1257.34, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('167628', 'Laney', 'Mcintyre', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('148213', 'José', 'Hayes', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('148586', 'Tiffany', 'Mckee', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('156539', 'Sanai', 'Flores', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142766', 'Anaya', 'Anthony', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('181966', 'Heath', 'Crosby', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134246', 'Brent', 'Lozano', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('179685', 'Jerônimo', 'Warren', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('188124', 'Simone', 'Cuevas', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('155696', 'Jayson', 'Reed', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('167527', 'Darnell', 'Duffy', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('160955', 'Laila', 'Arenque', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('185261', 'Alejandra', 'Middleton', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('172280', 'Katie', 'Macknight', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('128757', 'Jillian', 'Wu', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('190963', 'Chaya', 'Petty', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('135620', 'Kelsey', 'Simpson', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142415', 'Lizzie', 'Werner', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('157094', 'Jasmine', 'Hicks', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('125786', 'Adison', 'Medina', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('110201', 'Aliya', 'Callahan', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('199876', 'Paciência', 'Buchanan', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169275', 'Bria', 'Morse', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('109970', 'Jadiel', 'Liu', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('162700', 'Brent', 'Everett', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('121720', 'Ernesto', 'Henson', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('129971', 'Jay', 'Lucas', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('147634', 'Nickolas', 'Valdez', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('137374', 'Aliya', 'Higgins', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169516', 'Hugo', 'Mayer', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169149', 'Cale', 'Le', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('147839', 'Dayami', 'Caim', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('124438', 'Kiley', 'Nguyen', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('150775', 'Brielle', 'Logan', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('191071', 'Jaylyn', 'Hunter', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('130831', 'Kasen', 'Hammond', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('173035', 'Gerald', 'Owens', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('148259', 'Courtney', 'Bradshaw', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('151668', 'Darren', 'Robles', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('196327', 'Jordyn', 'Barba', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('135314', 'Cooper', 'Henrique', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('156796', 'Zachary', 'Dickerson', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('166682', 'Ashley', 'Macdowell', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('152516', 'Dayana', 'Bruce', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('123519', 'Reese', 'Spencer', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('182230', 'Andreas', 'Fitzpatrick', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('112005', 'Emmett', 'Whitaker', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('114539', 'Eliana', 'Henderson', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('173836', 'Rei', 'Norris', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('173392', 'Ryleigh', 'Byrd', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('128279', 'Canhão', 'Mira', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('144948', 'Johan', 'Hatfield', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('120448', 'Anton', 'Mcbride', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('122862', 'Igreja', 'Maria', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('112317', 'Chana', 'Frost', 2, 3976.57, 1, 'operador', 42)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('116422', 'Alex', 'OConnor', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('165497', 'Abigail', 'Mack', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('191863', 'Weston', 'Woods', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('113129', 'Glenn', 'Jones', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('128929', 'Deven', 'Gonzalez', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('161965', 'Gilberto', 'Woodward', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('183748', 'Gregório', 'Normando', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('156117', 'Destinee', 'Barton', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('159259', 'Shane', 'Higgins', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('180228', 'Amaya', 'Wallace', 1, 1257.34, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('162131', 'Eduardo', 'Coffey', 2, 3976.57, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('197136', 'Simon', 'Crosby', 2, 3976.57, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('198788', 'Gabriella', 'Obrien', 2, 3976.57, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('187175', 'Maddox', 'Lara', 2, 3976.57, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('196414', 'Selena', 'Silva', 2, 3976.57, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('178811', 'Adelaide', 'Gomez', 2, 3976.57, 1, 'operador', 43)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('133601', 'Jasmine', 'Caim', 1, 1257.34, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('122179', 'Amiyah', 'Orozco', 1, 1257.34, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('186150', 'Jamari', 'Nash', 1, 1257.34, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('132454', 'Barrett', 'Thompson', 1, 1257.34, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('155954', 'Shea', 'Sheppard', 1, 1257.34, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('175605', 'Zaniyah', 'Barron', 1, 1257.34, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('166076', 'CampbellKim', '', 2, 3976.57, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('149493', 'Denise', 'Larson', 2, 3976.57, 1, 'operador', 44)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('189411', 'Evangeline', 'Sanches', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('175674', 'Mariam', 'Fowler', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('116969', 'Jamari', 'Mosley', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142490', 'Tânia', 'Moreno', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('171536', 'Muralha', 'de', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('148649', 'Capa', 'lírica', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142291', 'Marlon', 'Parker', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('158539', 'Aden', 'Lowery', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('180146', 'Reynaldo', 'Yu', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('197747', 'Skyler', 'Howell', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('195280', 'Evie', 'Guerra', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('173389', 'Sammy', 'Downs', 1, 1257.34, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('157177', 'Alden', 'Hart', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('199629', 'Cláudia', 'Bautista', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('149099', 'Angelique', 'Roy', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('113040', 'Rey', 'Carey', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169549', 'Isabelle', 'Abbott', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('111821', 'Trent', 'Yang', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('159582', 'Yadira', 'Patrick', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('146399', 'Athena', 'Oconnell', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('182855', 'Kolten', 'Byrd', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('195063', 'Keagan', 'Pierce', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('190964', 'Jan', 'Proctor', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('133490', 'Lilyana', 'Stevenson', 2, 3976.57, 1, 'operador', 45)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('150417', 'Bryce', 'Chase', 1, 1257.34, 1, 'operador', 46)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('185311', 'Corvo', 'Bush', 1, 1257.34, 1, 'operador', 46)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('161490', 'Mollie', 'Alexandre', 1, 1257.34, 1, 'operador', 46)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('186088', 'Presley', 'Carrol', 2, 3976.57, 1, 'operador', 46)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('193977', 'Yaritza', 'Irwin', 2, 3976.57, 1, 'operador', 46)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('116950', 'Victor', 'Stein', 2, 3976.57, 1, 'operador', 46)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('180653', 'Hayden', 'Guerra', 1, 1257.34, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('137662', 'Frederico', 'Tucker', 1, 1257.34, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192539', 'Jacqueline', 'Mcneil', 1, 1257.34, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('118969', 'Alivia', 'Macknight', 1, 1257.34, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('119360', 'Amira', 'Costa', 1, 1257.34, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('125805', 'Ashlee', 'Barreira', 1, 1257.34, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('177424', 'Nola', 'Sloan', 2, 3976.57, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('117863', 'Dashawn', 'Tecelão', 2, 3976.57, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('184363', 'Salgueiro', 'Schwartz', 2, 3976.57, 1, 'operador', 47)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('193966', 'Walker', 'Santos', 1, 1257.31, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('129716', 'Gabriella', 'Pequena', 1, 1257.31, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('111765', 'Álvaro', 'Dillon', 1, 1257.31, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('131046', 'Aylin', 'Patel', 1, 1257.31, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('109190', 'Chanel', 'Walker', 1, 1257.31, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('185416', 'Rosa', 'Pearson', 1, 1257.31, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192542', 'Amara', 'Bautista', 2, 3976.76, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('121466', 'Judá', 'Sanford', 2, 3976.76, 1, 'operador', 48)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('138627', 'Ricardo', 'Hurst', 1, 1257.34, 1, 'operador', 41)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('194586', 'Saul', 'Jones', 1, 1257.34, 1, 'operador', 41)

INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('109026', 'Jaqueline', 'Lara', 2, 5566.36, 1, 'adm', 2)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('135307', 'Aditya', 'Rodes', 2, 5566.36, 1, 'adm', 2)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('110312', 'Jaslene', 'Lindsey', 2, 5566.36, 1, 'adm', 3)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('182143', 'Geraldo', 'Méndez', 2, 5566.36, 1, 'adm', 3)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('122921', 'Cade', 'Villegas', 2, 5566.36, 1, 'adm', 3)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('194947', 'Luis', 'Sloan', 2, 5566.36, 1, 'adm', 3)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('183155', 'Cindy', 'Krueger', 2, 5566.36, 1, 'adm', 3)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('165749', 'Aleena', 'Goodman', 2, 5566.36, 1, 'adm', 3)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('125874', 'Camryn', 'Phelps', 2, 5566.36, 1, 'adm', 3)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('186453', 'Angela', 'Guindaste', 2, 5566.36, 1, 'adm', 4)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('109781', 'Hadley', 'Leblanc', 2, 5566.36, 1, 'adm', 4)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('196068', 'Adriano', 'Wheeler', 2, 5566.36, 1, 'adm', 4)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('164972', 'Kolton', 'Gonzales', 2, 5566.36, 1, 'adm', 5)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('160340', 'Brenden', 'Leblanc', 2, 5566.36, 1, 'adm', 5)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('122174', 'Jasmim', 'Smith', 2, 5566.36, 1, 'adm', 5)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('119915', 'Porter', 'Suárez', 2, 5566.36, 1, 'adm', 5)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('157624', 'Rubi', 'OConnor', 2, 5566.36, 1, 'adm', 5)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169798', 'Amina', 'Lam', 2, 3780, 1, 'adm', 10)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134339', 'Agustín', 'Galloway', 2, 3780, 1, 'adm', 10)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142697', 'Clarence', 'Pham', 2, 3780, 1, 'adm', 10)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('151525', 'Alberto', 'Kennedy', 2, 3780, 1, 'adm', 10)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('125511', 'Katrina', 'Eaton', 2, 3780, 1, 'adm', 10)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('162896', 'Averie', 'Myers', 2, 3780, 1, 'adm', 10)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('181662', 'Ariel', 'Calhoun', 2, 3780, 1, 'adm', 10)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('114948', 'Mason', 'Shaw', 2, 3780, 1, 'adm', 11)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('167896', 'Maxim', 'Mcintyre', 2, 3780, 1, 'adm', 11)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('120689', 'Grant', 'Álvarez', 2, 3780, 1, 'adm', 11)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('194745', 'Cristian', 'Moss', 2, 3780, 1, 'adm', 11)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('149224', 'Cruz', 'Mclaughlin', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('176480', 'Príncipe', 'Bell', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('126639', 'Jeremias', 'Haas', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169247', 'Giovanna', 'Mcmahon', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('142517', 'Kirsten', 'Gordon', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('184150', 'Anaya', 'Zavala', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('120061', 'Máximo', 'Flynn', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('118971', 'Érica', 'Powers', 2, 3780, 1, 'adm', 12)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('150232', 'Wyatt', 'Woodward', 2, 3780, 1, 'adm', 13)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('140180', 'Kevin', 'Roth', 2, 3780, 1, 'adm', 13)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('139781', 'Tabita', 'Pace', 2, 3780, 1, 'adm', 13)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134587', 'Alma', 'Ochoa', 2, 3780, 1, 'adm', 15)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('159483', 'Nyla', 'Grant', 2, 3780, 1, 'adm', 15)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134422', 'Wade', 'Patel', 2, 3780, 1, 'adm', 15)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('120511', 'Samir', 'Bass', 2, 3780, 1, 'adm', 15)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('148287', 'Rolando', 'Roth', 2, 3780, 1, 'adm', 16)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('128149', 'Milagres', 'Quinn', 2, 3700, 1, 'adm', 18)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('172201', 'Pássaro', 'McKenzie', 2, 3700, 1, 'adm', 18)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('196938', 'Demétrio', 'McLean', 2, 3700, 1, 'adm', 18)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('160603', 'Caitlyn', 'Zimmerman', 2, 3700, 1, 'adm', 18)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('185625', 'Christopher', 'Roberts', 2, 3824.54, 1, 'adm', 19)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('189496', 'Dayami', 'Curtidor', 2, 3800, 1, 'adm', 20)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('138312', 'Cornélio', 'Olson', 2, 3800, 1, 'adm', 21)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('128489', 'Alana', 'White', 2, 3800, 1, 'adm', 22)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('140618', 'Refúgio', 'Lucero', 2, 3800, 1, 'adm', 22)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('165968', 'Kadence', 'Brandt', 2, 3800, 1, 'adm', 23)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('134709', 'Greyson', 'Avery', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('169646', 'Emerson', 'Terry', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('113779', 'Aaliyah', 'Wilkinson', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('138226', 'Erin', 'Webster', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('179981', 'Elsie', 'Hanna', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('162623', 'Porter', 'Robbins', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('157107', 'Amiyah', 'Craig', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('114442', 'Rex', 'Lucero', 2, 3800, 1, 'adm', 25)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('197429', 'Brennan', 'Garcia', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('186898', 'Brycen', 'Dawson', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('168424', 'Jogo', 'Jagger', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('136528', 'Chasity', 'Johnson', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('177800', 'Ernesto', 'Sloan', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('144329', 'Michael', 'Curry', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('151466', 'Madeline', 'Gomez', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('129331', 'Lilah', 'Patel', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('171302', 'Yaritza', 'Nicholson', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('119149', 'Bridget', 'Lin', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('153599', 'Isabel', 'Ryan', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('154977', 'Saniya', 'Mullins', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('189390', 'Xiomara', 'Wilcox', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('115010', 'Noé', 'Ortega', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('117878', 'Eva', 'Maldonado', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('109318', 'Amir', 'Muñoz', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('192182', 'Savanah', 'Hess', 2, 3800, 1, 'adm', 26)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('197497', 'Stacy', 'Patrick', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('175970', 'Amara', 'Carrillo', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('139133', 'Lilian', 'McClure', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('194322', 'Kenzie', 'Águas', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('186674', 'Estande', 'de', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('146419', 'Landyn', 'Cruz', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('128481', 'Lance', 'Príncipe', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('111991', 'Emely', 'Hampton', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('141758', 'Aniyah', 'Browning', 2, 3800, 1, 'adm', 27)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('167975', 'Matilda', 'Olson', 2, 2300, 1, 'adm', 34)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('198658', 'Braden', 'Robles', 2, 2300, 1, 'adm', 34)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('144659', 'Antonio', 'Chávez', 2, 2300, 1, 'adm', 34)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('150819', 'Abdiel', 'Zhang', 2, 2300, 1, 'adm', 35)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('168897', 'Vila', 'Conor', 2, 2300, 1, 'adm', 36)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('127345', 'Walker', 'Parker', 2, 2300, 1, 'adm', 37)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('146468', 'Leon', 'Mays', 2, 2300, 1, 'adm', 38)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('164866', 'Emerson', 'Todd', 2, 2300, 1, 'adm', 39)
INSERT INTO tb_employee(employee_number, first_name, last_name, workforce, salary, allocation_time, job, sector_id) VALUES ('147324', 'Desmond', 'Lewis', 2, 2300, 1, 'adm', 39)

